### ISSUE TITLE
onLaikaReady - Cypress

### ISSUE THREAD

**Issue by jkossis** [zendesk/laika#42]
I appreciate everyone's efforts on adding this [new functionality](https://github.com/zendesk/laika/pull/33)!

That said, I am trying to integrate it into my cypress usage, and I'm struggling a little bit with it ... I can configure my app to add the interceptors in `onLaikaReady` for cypress runs only through env/config, but how can I get access to those interceptors? Based on the [usage guide for cypress](https://zendesk.github.io/laika/docs/usage-in-cypress), it looks like `laika` is just pulled off the window object.

In this case, perhaps storing them/making them retrievable would be useful (vs. just having a callback). The callback makes sense from a component/unit-test perspective, where the link and its options are explicitly defined, but less from the e2e/cypress perspective. Happy to contribute, but perhaps looking for some feedback/direction as well.

**Comment by niieani** [comment]
Hi @jkossis! That's a fair point. I would accept a contribution that reads from `globalThis.onLaikaReady` - a function or an array of functions to be executed synchronously with Laika's initialization. This way, one could run:

```js
globalThis.onLaikaReady = (laika) => {
  // some logic
}
```

before any other `<script>` was executed on the page, hence ensuring that it is called at the expected time.

Would that solve the issue you're describing?

**Comment by jkossis** [comment]
I'm still not sure, at least for the cypress use case, that using `globalThis` will solve this issue. You still end up running into the same problem of not having access to the interceptors that were configured in the app that is under test. Whether they were provided via the existing method or via the proposal above.

Perhaps I am missing something, but it seems that the only way to get access (in cypress) to interceptors configured in the app that is under test would be to have the initial interceptors stored in laika (similar to the initial effort on that PR, before it was generalized to the `onLaikaReady` callback). That way, after cypress plucks `laika` off of the window object, it could retrieve them.

Perhaps we could support both options?

**Comment by jkossis** [comment]
For example, if the app code was the following:

```
let interceptor;

globalThis.onLaikaReady = (laika) => {
  interceptor = laika.intercept({ operationName: 'foo' });
}

/* rest of app code below has access to the interceptor variable */
```

And the cypress code was the following:

```
describe('foo', () => {
  let laika;

  before(() => {
    cy.visit('/');
    cy.window().its('laika').then(instance => laika = instance);
  });

  it('should show devices and device settings', () => {
    /* how would I get access to the interceptor variable declared in the app code above, using only globalThis without additional storage? */
  });
});
```

**Comment by niieani** [comment]
Hi @jkossis! Why would you setup the interceptors in the app code instead of directly in the Cypress code?

I would do something like this:

```js
describe('foo', () => {
  let laika;
  let interceptor;

  before(() => {
    cy.visit('/', {
      onBeforeLoad: (window) => {
        window.onLaikaReady = (laikaInstance) => {
          laika = laikaInstance
          interceptor = laika.intercept({ operationName: 'foo' });
        }
      }
    });
  });

  it('should test foo stuff', () => {
    // interceptor and laika should both be accessible here
  });
});
```

**Comment by jkossis** [comment]
@niieani sorry for the delay, just getting back to this now. While dev'ing it out, it frustratingly wasn't working, only to come to realize it was the `on` prefix that was mysteriously causing issues (the browser reserves that for event emitter callbacks). 

Because of this, would just `laikaReady` be palatable?

**Comment by bbrzoska** [comment]
@jkossis how about `laikaReadyCallbacks`?
Sorry for getting back only now.
